name: Semgrep

on:
  workflow_dispatch:

  # Scan changed files in PRs, block on new issues only (existing issues ignored)
  #pull_request: {}

  # Scan all files on branches, block on any issues
  push:
  #   branches: ["master", "main"]

  # Schedule this job to run at a certain time, using cron syntax
  # Note that * is a special character in YAML so you have to quote this string
  # schedule:
  #   - cron: '30 0 1,15 * *' # scheduled for 00:30 UTC on both the 1st and 15th of the month

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    container:
      image: returntocorp/semgrep:0.108
    steps:
      # Fetch project source
      - uses: actions/checkout@v3
      - run: semgrep --config auto --sarif --output=semgrep.sarif --metrics=off --error --severity=ERROR

      - name: Setup jq environment
        id: setup-jq
        uses: urgn/setup-jq-action@v3.0.2

      # Remove the #nosemgrep suppressed findings
      - name: Remove the nosemgrep suppressed findings
        run: |
          cat semgrep.sarif | ${{ steps.setup-jq.outputs.jq-binary }} 'del(.runs[].results[] | select(.suppressions != null) )' > semgrep.filtered.sarif

      # Upload findings to GitHub Advanced Security Dashboard [step 2/2]
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.filtered.sarif
        if: always()
